### ISSUE TITLE
Implement the add command to support date

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#65]
Dependencies: #64 

Format: add "DESCRIPTION" [on/by] [today/tomorrow/DAY/DATE]

E.g.
1) add "Buy Milk" on Thursday
2) add "Complete Assignment" by 14 Oct
3) add "Study maths" today
4) add "Submit assignment" tomorrow

*NOTE:
1) The DATE has to be in DAY MONTH YEAR format where the year is optional
2) If year is not specified, it is assumed to be this year or next year depending on the current date. However, the result of the add will be displayed and so the user can check whether is the task added correctly.
3) The DAY in DATE has to be numeric.
4) The MONTH can be in short form or in full. E.g. Feb or February, Apr or April.
5) The YEAR also has to be numeric
6) The DAY not in DATE can be in short form or in full. E.g. Mon or Monday, Thur or Thursday.

Refer to issue #63

**Comment by 1o0p3r** [comment]
Finish such support for date
