### ISSUE TITLE
Implement the add command to support start time

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#66]
Dependencies: #65 

Format: add "DESCRIPTION" [on] [today/tomorrow/DAY/DATE] [at] [START_TIME]

E.g.
1) add "Buy groceries" on Sunday 10am
2) add "Buy presents" tomorrow at 12pm
3) add "Programming Workshop" on 23 Oct 9.30am
4) add "Eat dinner" at 6pm

*NOTE: 
1) The TIME has to be in 12-hour format.
2) A dot is used in the time format instead of a colon. E.g. 10.30am instead of 10:30am.
3) If date is not specified, it is assumed to be today or tomorrow depending on the current time.
However, the result of the add will be displayed and so the user can check whether is the task added correctly.

Refer to issue #63

**Comment by 1o0p3r** [comment]
Finish support for startTime
