### ISSUE TITLE
Implement the add command to support end time

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#67]
Dependencies: #65 

Format: add "DESCRIPTION" by [today/tomorrow/DAY/DATE] [END_TIME}

E.g.
1) add "Submit assignment" by tomorrow 6pm
2) add "Complete assignment" by Sunday 12.30pm
3) add "Send an email" by 16 October 6pm
4) add "Leave office" by 6pm

*NOTE:
1) The TIME has to be in 12-hour format.
2) A dot is used in the time format instead of a colon. E.g. 10.30am instead of 10:30am.
3) If date is not specified, it is assumed to be today or tomorrow depending on the current time.
However, the result of the add will be displayed and so the user can check whether is the task added correctly.

Refer to issue #63

**Comment by 1o0p3r** [comment]
Finish support for endTime
