### ISSUE TITLE
Implement the add command to support start time and end time

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#68]
Dependencies: #66 and #67 

Format: add "DESCRIPTION" [on] [today/tomorrow/DAY/DATE] [from] [START_TIME] [to] [END_TIME]

E.g.
1) add "Programming Workshop" on Sunday from 10am to 4pm
2) add "Flower Arrangement Workshop" on 23 October from 7.30pm to 9.30pm
3) add "Interview" tomorrow from 11am to 11.30am
4) add "Do maths assignment" from 2pm to 4pm

*NOTE:
1) If date is not specified, it is assumed to be today or tomorrow depending on the current time. However, the result of the add will be displayed and so the user can check whether is the task added correctly.

Refer to issue #63

**Comment by 1o0p3r** [comment]
Complete support startTime endTime
