### ISSUE TITLE
Implement the list command to support different list

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#72]
Dependencies: #71 

Format: list [todo/schedule/done/all]

E.g.
1) list todo
2) list schedule
3) list done
4) list all

*NOTE:
1) By default, example 1 will list everything that are not done unfiltered.
2) Example 4 will list everything that are done and not done unfiltered..

Refer to issue #70

**Comment by 1o0p3r** [comment]
Complete list to fulfil different list types
