### ISSUE TITLE
Implement the list command to filter by date

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#74]
Dependencies: #73 

Format: list todo/schedule/completed/"all tasks" on DATE

E.g.
1) list todo on 23 Oct
2) list all tasks on 25 December

*NOTE:
1) The "all tasks" does not need the quotation marks when used.
2) The DATE has to be in DAY MONTH YEAR format where year is optional.
3) If year is not specified, it is assumed to be the current year or next year depending on the current date.
4) The DAY has to be numeric.
5) The MONTH can be in short form or full. E.g. Oct or October, Dec or December.
6) The YEAR has to be numeric.

Refer to issue #70

**Comment by Drashti96** [comment]
NA anymore. Planned not to do it.
