### ISSUE TITLE
Implement the list command to filter by time

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#75]
Dependencies: #73 

Format: list todo/schedule/completed/"all tasks" at TIME

E.g.
1) list schedule at 2pm
2) list all tasks at 5.30pm

*NOTE:
1) The "all tasks" does not need to have the quotation marks when used.
2) The TIME has to be in 12-hour format.
3) A dot is used in the time format instead of colon. E.g. 4.30pm not 4:30pm.

Refer to issue #70

**Comment by Drashti96** [comment]
NA anymore. Planned not to do it.
