### ISSUE TITLE
Implement the list command to filter by priority

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#76]
Dependencies: #73 

Format: list todo/schedule/completed/"all tasks" with PRIORITY

E.g.
1) list completed with high
2) list all tasks with medium

*NOTE:
1) The "all tasks" does not need to have the quotation marks when used.
2) The PRIORITY has to be low, medium or high.

Refer to issue #70

**Comment by Drashti96** [comment]
NA anymore. Planned not to do it.
