### ISSUE TITLE
Implement the update command to support todo tasks

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#82]
Dependencies: #81 

Format: update todo INDEX description/date/time/start/end/priority NEW_VALUE

E.g.
1) update todo 1 description Go shopping
2) update todo 4 date 22 Oct
3) update todo 5 time 2pm
4) update todo 10 priority medium

*NOTE:
1) The INDEX has to be numeric and a valid index of a todo task in the current todo list.
2) If time is used, it means there is only one timing for that task, no start and end time.

Refer to issue #81

**Comment by 1o0p3r** [comment]
Able to support todo for update
