### ISSUE TITLE
Implement the update command to support scheduled task

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#83]
Dependencies: #81 

Format: update schedule INDEX description/date/time/start/end/priority NEW_VALUE

E.g.
1) update schedule 1 description Buy clothes
2) update schedule 7 time 2pm
3) update schedule 9 end 4pm
4) update schedule 12 priority low

*NOTE:
1) The INDEX has to be numeric and a valid index of a scheduled task in the current schedule list.
2) If time is used, it means there is only one timing for that task, no start and end time.

Refer to issue #81

**Comment by 1o0p3r** [comment]
Complete update on schedule task
