### ISSUE TITLE
Implement the update command to support completed tasks

### ISSUE THREAD

**Issue by Verbena** [CS2103AUG2016-W15-C4/main#84]
Dependencies: #81 

Format: update completed INDEX description/date/time/start/end/priority NEW_VALUE

E.g.
1) update completed 1 description Buy chocolate milk
2) update completed 3 start 2pm
3) update completed 8 time 4pm
4) update completed 10 priority high

*NOTE:
1) The INDEX has to be numeric and a valid index of a todo task in the current todo list.
2) If time is used, it means there is only one timing for that task, no start and end time.

Refer to issue #81

**Comment by 1o0p3r** [comment]
Complete update for completedTask
